"""v1 auth + candidatures

Revision ID: 01570018ef3d
Revises: 
Create Date: 2026-07-03 14:33:03.379526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01570018ef3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_invites',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('admin_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_invites_email'), ['email'], unique=False)

    op.create_table('admin_notifs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('target_role', sa.String(length=20), nullable=True),
    sa.Column('title_fr', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('href', sa.String(length=120), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=160), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pub', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('type_fr', sa.String(length=160), nullable=True),
    sa.Column('type_en', sa.String(length=160), nullable=True),
    sa.Column('title_fr', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('desc_fr', sa.Text(), nullable=True),
    sa.Column('desc_en', sa.Text(), nullable=True),
    sa.Column('countries', sa.JSON(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('opens', sa.JSON(), nullable=True),
    sa.Column('deadline', sa.String(length=10), nullable=True),
    sa.Column('cap', sa.Integer(), nullable=True),
    sa.Column('apps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscribers_email'), ['email'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('member_type', sa.String(length=20), nullable=False),
    sa.Column('admin_role', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('applications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.String(length=10), nullable=True),
    sa.Column('assignee', sa.String(length=160), nullable=True),
    sa.Column('candidate_email', sa.String(length=255), nullable=True),
    sa.Column('candidat', sa.JSON(), nullable=True),
    sa.Column('projet', sa.JSON(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('besoins', sa.Text(), nullable=True),
    sa.Column('pieces', sa.JSON(), nullable=True),
    sa.Column('complements', sa.JSON(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_candidate_email'), ['candidate_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_candidate_email'))
        batch_op.drop_index(batch_op.f('ix_applications_call_id'))

    op.drop_table('applications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_email'))

    op.drop_table('subscribers')
    op.drop_table('contacts')
    op.drop_table('calls')
    op.drop_table('audit_log')
    op.drop_table('admin_notifs')
    with op.batch_alter_table('admin_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_invites_email'))

    op.drop_table('admin_invites')
    # ### end Alembic commands ###
