"""content table (news/events/pages)

Revision ID: 97601ddd09d1
Revises: 2f34cf243e43
Create Date: 2026-07-04 15:31:44.577274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97601ddd09d1'
down_revision = '2f34cf243e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('pub', sa.String(length=16), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('kind', 'slug', name='uq_content_kind_slug')
    )
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_slug'), ['slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_slug'))
        batch_op.drop_index(batch_op.f('ix_content_kind'))

    op.drop_table('content')
    # ### end Alembic commands ###
