"""threads + messages

Revision ID: a61159b126c7
Revises: 97601ddd09d1
Create Date: 2026-07-04 16:43:38.340063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61159b126c7'
down_revision = '97601ddd09d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('subject', sa.JSON(), nullable=True),
    sa.Column('with_name', sa.String(length=160), nullable=True),
    sa.Column('with_email', sa.String(length=255), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('closed_by', sa.JSON(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('thread_id', sa.String(length=80), nullable=True),
    sa.Column('sender', sa.JSON(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('at', sa.String(length=32), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_thread_id'), ['thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_thread_id'))

    op.drop_table('messages')
    op.drop_table('threads')
    # ### end Alembic commands ###
