"""enrich subscribers + contacts

Revision ID: ae3d58c9d192
Revises: b67353ba2145
Create Date: 2026-07-05 12:14:36.391204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3d58c9d192'
down_revision = 'b67353ba2145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('pays', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=False))

    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('read')
        batch_op.drop_column('pays')
        batch_op.drop_column('org')

    # ### end Alembic commands ###
