"""mentor_requests

Revision ID: ed528d6433bd
Revises: a61159b126c7
Create Date: 2026-07-04 16:57:25.317867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed528d6433bd'
down_revision = 'a61159b126c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_requests',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('mentor_id', sa.String(length=80), nullable=True),
    sa.Column('mentor_name', sa.String(length=160), nullable=True),
    sa.Column('from_user_id', sa.String(length=64), nullable=True),
    sa.Column('from_name', sa.String(length=160), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentor_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentor_requests_mentor_id'), ['mentor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentor_requests_mentor_id'))

    op.drop_table('mentor_requests')
    # ### end Alembic commands ###
