"""mentorships + sessions

Revision ID: f55f853029e7
Revises: ed528d6433bd
Create Date: 2026-07-04 17:13:35.034423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55f853029e7'
down_revision = 'ed528d6433bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_sessions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('mentor_id', sa.String(length=80), nullable=True),
    sa.Column('mentee_name', sa.String(length=160), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('scheduled_at', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentor_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentor_sessions_mentor_id'), ['mentor_id'], unique=False)

    op.create_table('mentorships',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('mentor_id', sa.String(length=80), nullable=True),
    sa.Column('mentee_name', sa.String(length=160), nullable=True),
    sa.Column('mentee_email', sa.String(length=255), nullable=True),
    sa.Column('mentee_org', sa.String(length=160), nullable=True),
    sa.Column('mentee_sector', sa.String(length=80), nullable=True),
    sa.Column('mentee_country', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentorships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentorships_mentor_id'), ['mentor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentorships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentorships_mentor_id'))

    op.drop_table('mentorships')
    with op.batch_alter_table('mentor_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentor_sessions_mentor_id'))

    op.drop_table('mentor_sessions')
    # ### end Alembic commands ###
